port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - https://dns.google/dns-query
proxies:
- name: claw新加坡-500GB
  type: vless
  server: 47.82.159.125
  port: 443
  uuid: 01909cc5-ec86-4d02-92a5-c78107bd8ffe
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: www.paypal.com
  reality-opts:
    public-key: p3UlTxt621sz_HTd4zSVwIlzWe8kgTdmN4XE1kSsSEk
    short-id: ''
  client-fingerprint: chrome
# claw东京 (47.79.92.99) 已移除 — 专用 TikTok 直播中转，不再用于个人翻墙
- name: jtti日本-无限
  type: vless
  server: 103.110.221.239
  port: 443
  uuid: f8d5f3ec-f016-423e-b7df-9a5cb42ad2b7
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: www.paypal.com
  reality-opts:
    public-key: e0vPQxNUefMZrTjPDz66NXff3vilKQzBQENGw9wrhXo
    short-id: ''
  client-fingerprint: chrome
- name: jtti美国-无限-1
  type: vless
  server: 38.181.44.110
  port: 443
  uuid: a1611ab2-0d47-43a3-84a2-86d2b8173153
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: aws.amazon.com
  reality-opts:
    public-key: kH3tuMyM0Raqzx2uvFHiWYmbi81jkBUh7sXg2jo9AmA
    short-id: ''
  client-fingerprint: chrome
- name: jtti美国-无限-2
  type: vless
  server: 38.181.44.222
  port: 443
  uuid: fb0f881a-a67e-4300-9f1b-8af3dda5104e
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: dash.cloudflare.com
  reality-opts:
    public-key: u5oOKAa8eYjSgeOAt6VhaJY_kjHCRM3gRcB0iT5s_1I
    short-id: ''
  client-fingerprint: chrome
proxy-groups:
- name: 🚀 节点选择
  type: select
  proxies:
  - ♻️ 自动选择
  - claw新加坡-500GB
  - jtti日本-无限
  - jtti美国-无限-1
  - jtti美国-无限-2
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - claw新加坡-500GB
  - jtti日本-无限
  - jtti美国-无限-1
  - jtti美国-无限-2
- name: 🌍 国外媒体
  type: select
  proxies:
  - 🚀 节点选择
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - 🚀 节点选择
  - DIRECT
rules:
- DOMAIN-SUFFIX,google.com,🚀 节点选择
- DOMAIN-KEYWORD,google,🚀 节点选择
- DOMAIN,google.com,🚀 节点选择
- DOMAIN-SUFFIX,github.com,🚀 节点选择
- DOMAIN-SUFFIX,twitter.com,🚀 节点选择
- DOMAIN-SUFFIX,youtube.com,🚀 节点选择
- DOMAIN-SUFFIX,facebook.com,🚀 节点选择
- DOMAIN-SUFFIX,instagram.com,🚀 节点选择
- DOMAIN-SUFFIX,netflix.com,🌍 国外媒体
- GEOIP,CN,DIRECT
- MATCH,🐟 漏网之鱼
